### ISSUE TITLE
[Inference/Validation] Estimated Classification in Metadata & Interface

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#166]
## Tasks to complete

- [x] Display estimation on Capture screen
- [x] Store estimation with each sample
- [ ] EXTRA: Pre-process the estimation analysis for the PDF 

<hr/>

@DrBubbles42 

Nick, I forgot to have this test sub cross his arms and all 180 images are with his arms his side.

But, I believe this is a valid example of "arm sway". 

What do you think? 

![image](https://github.com/VisualPT/visualPT/assets/124405841/a2284de2-c4df-426a-ba0f-3d1353e59a6a)

**Comment by DrBubbles42** [comment]
If you would say this subject passed the test but did not follow the procedure by crossing the arms then we should label the data as invalid and not use it to train the model. A large portion of the success of the model is the consistency that is highlighted when Charlie went through the data and relabeled. The issue is if you think this is a static position then the model will likely classify it as sway because of the inconsistent arm position and decrease accuracy.

**Comment by Timothyrichpt** [comment]
Got it. Yes, that is the case. He was not waving his arms to recover balance, they were simply hanging down at his sides.

**Comment by Timothyrichpt** [comment]
I think they’re all labeled arm sway.

**Comment by DrBubbles42** [comment]
Just to be clear, if he is labeled as sway and is passing the test we should not include this in the training. The inconsistency in the arm crossing will negatively impact the accuracy

**Comment by Timothyrichpt** [comment]
OK, I will ask Charlie to remove those images from the database

**Comment by charlieforward9** [comment]
I will be implementing a simple function to check the detection output for crossed arms. If they are not crossed there will be a visual indicator.

**Comment by charlieforward9** [comment]
Planning to log the estimated classification from the model in the metadata and use that as an indicator on the validation interface. Allowing the user to press `OK` is the estimated classification is correct, while still leaving the original buttons in case the estimation is incorrect.

**Comment by charlieforward9** [comment]
Not included in #171 due to design of [Repository](https://github.com/VisualPT/visualPT/blob/09923d4e213264c05cac9c6474c320a7c99f3782/lib/core/services/repository.dart#L5) architecture, which saves the data of the input (image) with the output (detection), without including the output of a subsequent repository in the pipeline whos input is the detection.

A solution to this could be to pass the original input ID through to the classification repositorys `store` method and use the name of the file to match assets.

**Comment by charlieforward9** [comment]
Successfully created an output that combines all the helpful data from the image/detection/classification and packages it together into a graph schema.

The hierarchy is as follows: `User` -> `Subject` -> `Assessment` -> `Condition` -> `Trial` -> `Detection`

> -> means `has many`

Here is a printed output of the Detection data. This will gradually replace the CSV so we can store the data in an S3 database and use a custom API to manipulate data more freely.

```
Detection {
  id=1716349620184, 
  version=1, 
  obtrustion=false, 
  instability=false, 
  env=DetectionEnv {
    imageHeight=352, 
    imageWidth=288, 
    accX=-0.013008373752236367, 
    accY=0.005081815123558045, 
    accZ=0.2331401824951172, 
    gyroX=-0.01607510633766651,  
    gyroY=0.07911079376935959,  
    gyroZ=0.008343150839209557}, 
  keypoints=PoseDetectionOutput(
    [Offset(124.9, 50.2), Offset(126.9, 47.0), Offset(128.2, 46.8), Offset(129.6, 46.7), Offset(122.6, 47.7), Offset(121.3, 48.1), Offset(119.9, 48.4), Offset(132.5, 49.1), Offset(118.6, 51.1), Offset(128.2, 54.4), Offset(123.3, 55.3), Offset(147.1, 73.0), Offset(108.5, 74.7), Offset(170.5, 91.2), Offset(82.5, 91.4), Offset(154.0, 109.2), Offset(101.7, 105.1), Offset(148.9, 116.0), Offset(107.8, 110.3), Offset(145.5, 112.1), Offset(111.4, 107.9), Offset(147.3, 110.0), Offset(109.2, 106.1), Offset(138.3, 128.3), Offset(115.7, 128.4), Offset(147.1, 170.3), Offset(118.4, 169.8), Offset(137.3, 204.4), Offset(123.3, 209.4), Offset(135.7, 207.3), Offset(124.4, 213.6), Offset(132.3, 219.5), Offset(126.8, 224.6), Offset(126.9, 128.2), Offset(128.5, 28.2), Offset(146.8, 113.3), Offset(154.0, 109.3), Offset(110.1, 108.5), Offset(101.7, 105.2)], 
    [-157.9828338623047, -150.84530639648438, -150.9488525390625, -150.92965698242188, -150.45863342285156, -150.57823181152344, -150.6433868408203, -104.67350769042969, -102.40101623535156, -139.0541229248047, -139.21539306640625, -56.64508819580078, -58.020301818847656, -9.357749938964844, -25.340240478515625, -8.719573974609375, -33.1789665222168, -13.19395637512207, -42.22724533081055, -20.773061752319336, -45.265926361083984, -10.218706130981445, -34.224281311035156, 4.300136566162109, -4.364215850830078, -49.450172424316406, -44.776859283447266, 60.12620544433594, 42.98833465576172, 69.27674865722656, 50.246177673339844, 23.372634887695312, -0.4619293212890625, -0.16268447041511536, -0.9553296566009521, 0.6916940808296204, 0.582923948764801, 0.12325939536094666, 0.903425931930542], 
     [10.324474334716797, 9.530582427978516, 9.402347564697266, 10.045692443847656, 9.763870239257812, 9.654666900634766, 9.914085388183594, 10.180572509765625, 8.346565246582031, 10.917945861816406, 10.612258911132812, 12.040372848510742, 10.324047088623047, 4.096439361572266, 3.542236328125, 3.5698089599609375, 2.115795135498047, 2.7949447631835938, 1.2391891479492188, 2.8565101623535156, 1.2720260620117188, 2.4047164916992188, 0.844940185546875, 8.87850570678711, 8.658369064331055, 1.3334064483642578, 1.5794563293457031, 0.0397491455078125, 1.3277606964111328, -1.2140541076660156, -0.8569927215576172, 0.17132186889648438, 0.9595527648925781, -16.631820678710938, -16.7147216796875, -16.620277404785156, -16.539764404296875, -16.503509521484375, -16.64912223815918]), 
  prediction=1: arms uncrossed}, 
```

More details to come. [Click here to see the schema DRAFT](https://github.com/VisualPT/visualPT/blob/d0775ebe093ead6bc3bf60dde52beb89e51f0ee2/amplify/backend/api/visualpt/schema.graphql)

@DrBubbles42

**Comment by charlieforward9** [comment]
Part of a larger validation overhaul led by #172
